
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos {
  /* terminals */
  public static final int cconfig = 28;
  public static final int comilla = 12;
  public static final int xbloque = 6;
  public static final int ccorchete = 20;
  public static final int xtipo = 13;
  public static final int coma = 21;
  public static final int acorchete = 19;
  public static final int adesign = 2;
  public static final int numero = 17;
  public static final int xnombre = 23;
  public static final int xbomba = 8;
  public static final int afig = 10;
  public static final int xcreditos = 4;
  public static final int aback = 18;
  public static final int igual = 25;
  public static final int cdesign = 3;
  public static final int xmeta = 5;
  public static final int EOF = 0;
  public static final int xarma = 9;
  public static final int xvida = 31;
  public static final int aconfig = 26;
  public static final int xheroe = 14;
  public static final int error = 1;
  public static final int cfig = 11;
  public static final int pxnombre = 22;
  public static final int xenemigo = 15;
  public static final int xdescripcion = 29;
  public static final int cback = 27;
  public static final int xdestruir = 30;
  public static final int ximg = 24;
  public static final int puntoComa = 16;
  public static final int xbonus = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "adesign",
  "cdesign",
  "xcreditos",
  "xmeta",
  "xbloque",
  "xbonus",
  "xbomba",
  "xarma",
  "afig",
  "cfig",
  "comilla",
  "xtipo",
  "xheroe",
  "xenemigo",
  "puntoComa",
  "numero",
  "aback",
  "acorchete",
  "ccorchete",
  "coma",
  "pxnombre",
  "xnombre",
  "ximg",
  "igual",
  "aconfig",
  "cback",
  "cconfig",
  "xdescripcion",
  "xdestruir",
  "xvida"
  };
}

