
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers2;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141202 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class sintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return tabla_simbolos.class;
}

  /** Default constructor. */
  public sintactico() {super();}

  /** Constructor which sets the default scanner. */
  public sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\104\000\002\002\004\000\002\030\002\000\002\031" +
    "\002\000\002\032\002\000\002\002\021\000\002\003\003" +
    "\000\002\003\004\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\033\002\000\002" +
    "\005\006\000\002\034\002\000\002\035\002\000\002\036" +
    "\002\000\002\037\002\000\002\006\014\000\002\040\002" +
    "\000\002\010\006\000\002\011\010\000\002\011\010\000" +
    "\002\041\002\000\002\042\002\000\002\043\002\000\002" +
    "\044\002\000\002\012\014\000\002\013\003\000\002\013" +
    "\004\000\002\045\002\000\002\046\002\000\002\047\002" +
    "\000\002\050\002\000\002\014\014\000\002\015\003\000" +
    "\002\015\004\000\002\051\002\000\002\016\006\000\002" +
    "\017\010\000\002\017\010\000\002\052\002\000\002\053" +
    "\002\000\002\054\002\000\002\055\002\000\002\020\014" +
    "\000\002\056\002\000\002\057\002\000\002\060\002\000" +
    "\002\061\002\000\002\021\014\000\002\022\004\000\002" +
    "\022\003\000\002\062\002\000\002\007\006\000\002\063" +
    "\002\000\002\064\002\000\002\023\007\000\002\065\002" +
    "\000\002\024\007\000\002\024\004\000\002\066\002\000" +
    "\002\025\005\000\002\067\002\000\002\026\006\000\002" +
    "\026\003\000\002\027\004\000\002\070\002\000\002\027" +
    "\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\220\000\004\040\005\001\002\000\004\002\222\001" +
    "\002\000\004\030\006\001\002\000\004\037\000\001\002" +
    "\000\004\037\010\001\002\000\004\033\011\001\002\000" +
    "\004\031\012\001\002\000\004\032\uffff\001\002\000\004" +
    "\032\014\001\002\000\004\036\015\001\002\000\004\033" +
    "\016\001\002\000\004\031\017\001\002\000\004\035\ufffe" +
    "\001\002\000\004\035\021\001\002\000\012\005\022\007" +
    "\033\015\026\020\031\001\002\000\004\027\ufff6\001\002" +
    "\000\014\004\ufffc\005\022\007\033\015\026\020\031\001" +
    "\002\000\004\004\203\001\002\000\014\004\ufffa\005\ufffa" +
    "\007\ufffa\015\ufffa\020\ufffa\001\002\000\004\027\uffcd\001" +
    "\002\000\014\004\ufff9\005\ufff9\007\ufff9\015\ufff9\020\ufff9" +
    "\001\002\000\014\004\ufff7\005\ufff7\007\ufff7\015\ufff7\020" +
    "\ufff7\001\002\000\006\023\uffdd\025\uffdd\001\002\000\014" +
    "\004\ufff8\005\ufff8\007\ufff8\015\ufff8\020\ufff8\001\002\000" +
    "\006\011\uffef\013\uffef\001\002\000\006\011\036\013\035" +
    "\001\002\000\004\027\046\001\002\000\004\027\041\001" +
    "\002\000\004\010\040\001\002\000\014\004\uffee\005\uffee" +
    "\007\uffee\015\uffee\020\uffee\001\002\000\004\031\uffeb\001" +
    "\002\000\004\012\043\001\002\000\004\013\044\001\002" +
    "\000\004\027\046\001\002\000\004\014\062\001\002\000" +
    "\004\031\uffe4\001\002\000\004\031\050\001\002\000\004" +
    "\034\uffe3\001\002\000\004\034\052\001\002\000\004\031" +
    "\053\001\002\000\004\022\uffe2\001\002\000\004\022\055" +
    "\001\002\000\004\032\uffe1\001\002\000\004\032\060\001" +
    "\002\000\004\014\uffe0\001\002\000\006\014\uffdf\027\046" +
    "\001\002\000\004\014\uffde\001\002\000\004\010\uffed\001" +
    "\002\000\004\031\064\001\002\000\004\034\uffea\001\002" +
    "\000\004\034\066\001\002\000\004\031\067\001\002\000" +
    "\004\022\uffe9\001\002\000\004\022\071\001\002\000\004" +
    "\032\uffe8\001\002\000\004\032\074\001\002\000\004\012" +
    "\uffe7\001\002\000\006\012\uffe6\027\041\001\002\000\004" +
    "\012\uffe5\001\002\000\004\014\077\001\002\000\004\011" +
    "\100\001\002\000\004\027\041\001\002\000\004\012\102" +
    "\001\002\000\004\010\uffec\001\002\000\006\023\104\025" +
    "\106\001\002\000\004\027\114\001\002\000\004\021\142" +
    "\001\002\000\004\027\107\001\002\000\004\031\uffd4\001" +
    "\002\000\004\026\111\001\002\000\004\023\112\001\002" +
    "\000\004\027\114\001\002\000\004\024\126\001\002\000" +
    "\004\031\uffd9\001\002\000\004\031\116\001\002\000\004" +
    "\034\uffd8\001\002\000\004\034\120\001\002\000\004\031" +
    "\121\001\002\000\004\022\uffd7\001\002\000\004\022\123" +
    "\001\002\000\004\032\uffd6\001\002\000\004\032\125\001" +
    "\002\000\004\024\uffd5\001\002\000\004\021\uffda\001\002" +
    "\000\004\031\130\001\002\000\004\034\uffd3\001\002\000" +
    "\004\034\132\001\002\000\004\031\133\001\002\000\004" +
    "\022\uffd2\001\002\000\004\022\135\001\002\000\004\032" +
    "\uffd1\001\002\000\004\032\137\001\002\000\006\026\uffce" +
    "\027\107\001\002\000\004\026\uffd0\001\002\000\004\026" +
    "\uffcf\001\002\000\014\004\uffdc\005\uffdc\007\uffdc\015\uffdc" +
    "\020\uffdc\001\002\000\004\024\144\001\002\000\004\025" +
    "\145\001\002\000\004\027\107\001\002\000\004\026\147" +
    "\001\002\000\004\021\uffdb\001\002\000\004\027\152\001" +
    "\002\000\004\016\202\001\002\000\004\031\uffcb\001\002" +
    "\000\004\031\154\001\002\000\006\017\uffca\034\uffca\001" +
    "\002\000\006\017\156\034\160\001\002\000\004\031\176" +
    "\001\002\000\004\016\uffc9\001\002\000\004\031\161\001" +
    "\002\000\006\017\uffc5\022\uffc5\001\002\000\004\016\uffc6" +
    "\001\002\000\006\017\167\022\166\001\002\000\004\016" +
    "\uffc1\001\002\000\004\016\uffc4\001\002\000\004\032\173" +
    "\001\002\000\004\031\170\001\002\000\004\022\uffc3\001" +
    "\002\000\004\022\166\001\002\000\004\016\uffc2\001\002" +
    "\000\006\016\uffc0\027\uffbf\001\002\000\004\027\152\001" +
    "\002\000\004\016\uffbe\001\002\000\004\034\uffc8\001\002" +
    "\000\004\034\200\001\002\000\004\031\161\001\002\000" +
    "\004\016\uffc7\001\002\000\014\004\uffcc\005\uffcc\007\uffcc" +
    "\015\uffcc\020\uffcc\001\002\000\004\002\ufffd\001\002\000" +
    "\004\004\ufffb\001\002\000\004\027\207\001\002\000\004" +
    "\006\221\001\002\000\004\031\ufff4\001\002\000\004\031" +
    "\211\001\002\000\004\034\ufff3\001\002\000\004\034\213" +
    "\001\002\000\004\031\214\001\002\000\004\022\ufff2\001" +
    "\002\000\004\022\216\001\002\000\004\032\ufff1\001\002" +
    "\000\004\032\220\001\002\000\004\006\ufff0\001\002\000" +
    "\014\004\ufff5\005\ufff5\007\ufff5\015\ufff5\020\ufff5\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\220\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\030\006\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\031\012\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\032\017\001\001\000\002\001" +
    "\001\000\016\003\023\004\022\005\027\007\031\010\024" +
    "\016\026\001\001\000\004\033\204\001\001\000\016\003" +
    "\203\004\022\005\027\007\031\010\024\016\026\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\062\147\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\051\102" +
    "\001\001\000\002\001\001\000\004\040\033\001\001\000" +
    "\004\011\036\001\001\000\004\014\075\001\001\000\004" +
    "\012\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\041\062\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\044\001\001\000\002\001\001\000\004\045" +
    "\046\001\001\000\002\001\001\000\004\046\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\047\053\001" +
    "\001\000\002\001\001\000\004\050\055\001\001\000\004" +
    "\015\056\001\001\000\002\001\001\000\004\014\060\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\042\064\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\043\067\001\001\000\002\001\001\000\004" +
    "\044\071\001\001\000\004\013\072\001\001\000\002\001" +
    "\001\000\004\012\074\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\012\100\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\104\001\001" +
    "\000\004\020\142\001\001\000\002\001\001\000\004\021" +
    "\107\001\001\000\004\056\126\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\020\112\001\001\000\002\001" +
    "\001\000\004\052\114\001\001\000\002\001\001\000\004" +
    "\053\116\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\054\121\001\001\000\002\001\001\000\004\055\123" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\057\130\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\060\133\001\001\000" +
    "\002\001\001\000\004\061\135\001\001\000\004\022\137" +
    "\001\001\000\004\021\140\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\021\145\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\023\150\001\001\000\002\001\001" +
    "\000\004\063\152\001\001\000\002\001\001\000\004\064" +
    "\154\001\001\000\004\024\156\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\025\161\001\001\000\004\066" +
    "\162\001\001\000\002\001\001\000\006\026\164\027\163" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\067\170\001\001\000\004" +
    "\027\171\001\001\000\002\001\001\000\004\070\173\001" +
    "\001\000\004\023\174\001\001\000\002\001\001\000\004" +
    "\065\176\001\001\000\002\001\001\000\004\025\200\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\205\001\001\000\002\001" +
    "\001\000\004\034\207\001\001\000\002\001\001\000\004" +
    "\035\211\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\036\214\001\001\000\002\001\001\000\004\037\216" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



/**Metodo al que se llama automáticamente ante algún error sintactico.*/
public void syntax_error(Symbol s){
compi1_proyecto1.Menu.erroresText.setText(compi1_proyecto1.Menu.erroresText.getText().concat("\nError en la Línea " + (s.right+1) + ". Columna " + s.left + ". Identificador " + s.value + " no reconocido." ));
compi1_proyecto1.Compi1_Proyecto1.otroArch2();
}

/**Metodo al que se llama en el momento en que ya no es posible una recuperación de errores.*/
public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
compi1_proyecto1.Menu.erroresText.setText(compi1_proyecto1.Menu.erroresText.getText().concat("\nError en la Línea " + (s.right+1) + ". Columna " + s.left + ". Identificador " + s.value + " no reconocido." ));
compi1_proyecto1.Compi1_Proyecto1.otroArch2();
}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$sintactico$actions {
  private final sintactico parser;

  /** Constructor */
  CUP$sintactico$actions(sintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$sintactico$do_action_part00000000(
    int                        CUP$sintactico$act_num,
    java_cup.runtime.lr_parser CUP$sintactico$parser,
    java.util.Stack            CUP$sintactico$stack,
    int                        CUP$sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$sintactico$result;

      /* select the action based on the action number */
      switch (CUP$sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIA EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
		RESULT = start_val;
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$sintactico$parser.done_parsing();
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.saveFondo((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$0",22, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-3)).value;
compi1_proyecto1.Compi1_Proyecto1.setAncho((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$1",23, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // NT$2 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-4)).value;
compi1_proyecto1.Compi1_Proyecto1.setAlto((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$2",24, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INICIA ::= aEscenario pxnombre NT$0 tancho igual numero NT$1 puntoComa talto igual numero NT$2 mayorQue S cEscenario 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-3)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("INICIA",0, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-14)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // S ::= SA 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("S",1, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // S ::= SA S 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("S",1, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SA ::= EXTRAS_START 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("SA",2, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SA ::= PERSON_START 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("SA",2, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SA ::= PAREDES_START 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("SA",2, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SA ::= META_START 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("SA",2, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$3 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$3",25, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // META_START ::= axmeta NT$3 META_B cxmeta 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("META_START",3, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NT$4 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();compi1_proyecto1.Compi1_Proyecto1.updateNameArch2((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$4",26, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // NT$5 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.setXini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$5",27, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$6 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;
compi1_proyecto1.Compi1_Proyecto1.setYini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$6",28, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$7 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.setMeta();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$7",29, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // META_B ::= pnombre NT$4 numero NT$5 coma numero NT$6 cParen NT$7 puntoComa 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("META_B",4, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-9)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // NT$8 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$8",30, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // EXTRAS_START ::= axextras NT$8 EXTRAS_B cxextras 
            {
              Object RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_START",6, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // EXTRAS_B ::= axarmas EXTRAS_C cxarmas axbonus EXTRAS_E cxbonus 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_B",7, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // EXTRAS_B ::= axbonus EXTRAS_E cxbonus axarmas EXTRAS_C cxarmas 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_B",7, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // NT$9 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();compi1_proyecto1.Compi1_Proyecto1.updateNameArch2((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$9",31, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$10 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.setXini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$10",32, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // NT$11 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;
compi1_proyecto1.Compi1_Proyecto1.setYini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$11",33, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$12 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.activarArma();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$12",34, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // EXTRAS_C ::= pnombre NT$9 numero NT$10 coma numero NT$11 cParen NT$12 EXTRAS_D 
            {
              Object RESULT =null;
              // propagate RESULT from NT$12
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_C",8, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-9)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // EXTRAS_D ::= puntoComa 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_D",9, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // EXTRAS_D ::= puntoComa EXTRAS_C 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_D",9, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$13 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();compi1_proyecto1.Compi1_Proyecto1.updateNameArch2((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$13",35, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // NT$14 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.setXini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$14",36, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // NT$15 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;
compi1_proyecto1.Compi1_Proyecto1.setYini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$15",37, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // NT$16 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.activarBonus();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$16",38, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // EXTRAS_E ::= pnombre NT$13 numero NT$14 coma numero NT$15 cParen NT$16 EXTRAS_F 
            {
              Object RESULT =null;
              // propagate RESULT from NT$16
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_E",10, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-9)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // EXTRAS_F ::= puntoComa 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_F",11, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // EXTRAS_F ::= puntoComa EXTRAS_E 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("EXTRAS_F",11, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // NT$17 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$17",39, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // PERSON_START ::= apersonas NT$17 PERSON_B cpersonas 
            {
              Object RESULT =null;
              // propagate RESULT from NT$17
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PERSON_START",12, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // PERSON_B ::= aheroe PERSON_C cheroe avillanos PERSON_E cvillanos 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PERSON_B",13, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // PERSON_B ::= avillanos PERSON_E cvillanos aheroe PERSON_C cheroe 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PERSON_B",13, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // NT$18 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();compi1_proyecto1.Compi1_Proyecto1.updateNameArch2((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$18",40, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // NT$19 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.setXini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$19",41, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // NT$20 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;
compi1_proyecto1.Compi1_Proyecto1.setYini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$20",42, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // NT$21 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.activarHeroe();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$21",43, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // PERSON_C ::= pnombre NT$18 numero NT$19 coma numero NT$20 cParen NT$21 puntoComa 
            {
              Object RESULT =null;
              // propagate RESULT from NT$21
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PERSON_C",14, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-9)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // NT$22 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();compi1_proyecto1.Compi1_Proyecto1.updateNameArch2((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$22",44, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // NT$23 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.setXini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$23",45, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // NT$24 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;
compi1_proyecto1.Compi1_Proyecto1.setYini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$24",46, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // NT$25 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.activarEnemigo();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$25",47, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // PERSON_E ::= pnombre NT$22 numero NT$23 coma numero NT$24 cParen NT$25 PERSON_F 
            {
              Object RESULT =null;
              // propagate RESULT from NT$25
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PERSON_E",15, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-9)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // PERSON_F ::= puntoComa PERSON_E 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PERSON_F",16, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // PERSON_F ::= puntoComa 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PERSON_F",16, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // NT$26 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$26",48, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // PAREDES_START ::= aparedes NT$26 PAREDES_H cparedes 
            {
              Object RESULT =null;
              // propagate RESULT from NT$26
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_START",5, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // NT$27 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.resetAllNew(); compi1_proyecto1.Compi1_Proyecto1.setNamePared((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$27",49, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // NT$28 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;
compi1_proyecto1.Compi1_Proyecto1.setXini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$28",50, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // PAREDES_H ::= pnombre NT$27 numero NT$28 PAREDES_I 
            {
              Object RESULT =null;
              // propagate RESULT from NT$28
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_H",17, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // NT$29 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.setXfinal((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$29",51, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // PAREDES_I ::= puntos numero NT$29 coma PAREDES_J 
            {
              Object RESULT =null;
              // propagate RESULT from NT$29
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_I",18, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // PAREDES_I ::= coma PAREDES_J 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_I",18, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // NT$30 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.setYini((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$30",52, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // PAREDES_J ::= numero NT$30 PAREDES_K 
            {
              Object RESULT =null;
              // propagate RESULT from NT$30
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_J",19, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // NT$31 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.setYfinal((String) (((java_cup.runtime.Symbol) CUP$sintactico$stack.peek()).value));
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$31",53, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // PAREDES_K ::= puntos numero NT$31 PAREDES_L 
            {
              Object RESULT =null;
              // propagate RESULT from NT$31
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_K",20, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // PAREDES_K ::= PAREDES_L 
            {
              Object RESULT =null;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_K",20, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // PAREDES_L ::= cParen puntoComa 
            {
              Object RESULT =null;
		compi1_proyecto1.Compi1_Proyecto1.nuevaPared();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_L",21, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // NT$32 ::= 
            {
              Object RESULT =null;
compi1_proyecto1.Compi1_Proyecto1.nuevaPared();
              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("NT$32",54, ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // PAREDES_L ::= cParen puntoComa NT$32 PAREDES_H 
            {
              Object RESULT =null;
              // propagate RESULT from NT$32
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$sintactico$stack.elementAt(CUP$sintactico$top-1)).value;

              CUP$sintactico$result = parser.getSymbolFactory().newSymbol("PAREDES_L",21, ((java_cup.runtime.Symbol)CUP$sintactico$stack.elementAt(CUP$sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$sintactico$stack.peek()), RESULT);
            }
          return CUP$sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$sintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$sintactico$do_action(
    int                        CUP$sintactico$act_num,
    java_cup.runtime.lr_parser CUP$sintactico$parser,
    java.util.Stack            CUP$sintactico$stack,
    int                        CUP$sintactico$top)
    throws java.lang.Exception
    {
              return CUP$sintactico$do_action_part00000000(
                               CUP$sintactico$act_num,
                               CUP$sintactico$parser,
                               CUP$sintactico$stack,
                               CUP$sintactico$top);
    }
}

}
