
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package Parsers2;

/** CUP generated class containing symbol constants. */
public class tabla_simbolos {
  /* terminals */
  public static final int cxbonus = 10;
  public static final int coma = 26;
  public static final int cparedes = 12;
  public static final int axarmas = 7;
  public static final int numero = 23;
  public static final int tancho = 29;
  public static final int cEscenario = 2;
  public static final int axmeta = 3;
  public static final int cxextras = 6;
  public static final int axextras = 5;
  public static final int aEscenario = 30;
  public static final int igual = 25;
  public static final int EOF = 0;
  public static final int cxarmas = 8;
  public static final int cxmeta = 4;
  public static final int aparedes = 11;
  public static final int error = 1;
  public static final int pxnombre = 22;
  public static final int aheroe = 17;
  public static final int axbonus = 9;
  public static final int cvillanos = 20;
  public static final int avillanos = 19;
  public static final int puntos = 13;
  public static final int puntoComa = 24;
  public static final int pnombre = 21;
  public static final int talto = 28;
  public static final int cpersonas = 15;
  public static final int apersonas = 14;
  public static final int mayorQue = 27;
  public static final int cheroe = 18;
  public static final int cParen = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cEscenario",
  "axmeta",
  "cxmeta",
  "axextras",
  "cxextras",
  "axarmas",
  "cxarmas",
  "axbonus",
  "cxbonus",
  "aparedes",
  "cparedes",
  "puntos",
  "apersonas",
  "cpersonas",
  "cParen",
  "aheroe",
  "cheroe",
  "avillanos",
  "cvillanos",
  "pnombre",
  "pxnombre",
  "numero",
  "puntoComa",
  "igual",
  "coma",
  "mayorQue",
  "talto",
  "tancho",
  "aEscenario"
  };
}

